# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, lens, primitive, QuickCheck, tasty, tastyQuickcheck
, transformers, vector, vectorAlgorithms
}:

cabal.mkDerivation (self: {
  pname = "sparse-linear";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [
    lens primitive transformers vector vectorAlgorithms
  ];
  testDepends = [ lens QuickCheck tasty tastyQuickcheck vector ];
  meta = {
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
